name: Build & Deploy to Cloudflare Pages

on:
  push:
    branches: [master]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
  pull_request:
    branches: [master]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      region:
        description: 'Region'
        required: true
        default: 'global'
      mode:
        description: 'Mode'
        required: true
        default: 'manual'
      open_message_id:
        description: 'Lark Message ID for callback'
        required: false

env:
  NODE_VERSION: 22.18.0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-and-deploy:
    # 集成分支的 push 一律构建；PR 仅在带 deploy 标签时构建（精确匹配）；workflow_dispatch 直接执行
    if: >-
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Setup Node & Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: /home/runner/setup-pnpm/node_modules/.bin/store
          key: pnpm-store-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-${{ env.NODE_VERSION }}-
            pnpm-store-${{ runner.os }}-

      - name: Prepare (version + install)
        id: prepare
        run: |
          npx --yes tsx .github/scripts/gen-version.ts
          pnpm install --frozen-lockfile --prefer-offline

      - name: Generate project list
        id: gen
        run: npx --yes tsx .github/scripts/list-projects.ts
        env:
          LAST_SHA: ${{ github.event.before || github.event.pull_request.base.sha || 'HEAD~1' }}
          HEAD_SHA: ${{ github.sha }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          OPEN_MESSAGE_ID: ${{ github.event.inputs.open_message_id }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          REGION: ${{ github.event.inputs.region || 'global' }}
          MODE: ${{ github.event.inputs.mode || 'manual' }}
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Build & Deploy projects sequentially
        if: ${{ steps.gen.outputs.pairs != '' }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PAIRS: ${{ steps.gen.outputs.pairs }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          REGION: ${{ github.event.inputs.region || 'global' }}
          MODE: ${{ github.event.inputs.mode || 'manual' }}
          OPEN_MESSAGE_ID: ${{ github.event.inputs.open_message_id }}
        run: |
          npx --yes tsx .github/scripts/build-and-deploy.ts
